name: Keep Docker Running on Codespaces

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours to prevent timeout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull bharshavardhanreddy924/deepfake_detection:latest

      - name: Stop and Remove Existing Container (if running)
        run: |
          docker stop deepfake_container || true
          docker rm deepfake_container || true

      - name: Run Docker Container
        run: |
          docker run -d --restart=always -p 8000:8000 --name deepfake_container bharshavardhanreddy924/deepfake_detection:latest

      - name: Keep Codespaces Alive
        run: nohup sleep infinity &
