name: Run Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Restart every 6 hours

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull and Run Docker Container
        run: |
          docker pull bharshavardhanreddy924/deepfake_detection:latest
          docker run -d -p 8080:8080 --restart=always bharshavardhanreddy924/deepfake_detection:latest
