name: Keep Codespace Alive
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep it alive
        run: curl -X GET https://github.com/codespaces
